### ISSUE TITLE
app not working for my code. please help

### ISSUE THREAD

**Issue by prajesh-pixel** [malbaugh/androidAdafruitBleExample#1]
i have added the new characteristics of the data i want to send from my ble compatible arduino nano 33 ble mcu and added a new viewmodel for my data as you have for the accelerometer but i am not able to display any data

**Comment by malbaugh** [comment]
Could be many things. I would first check to make sure your BLE device is transmitting the data from the component. You can download apps on your phone that will help you do that. Search for BLE sniffers - maybe try nRF Connect?

Once you confirm the BLE device is sending the data and you are getting the data, start adding in logs generously throughout your application to see if you are successfully reading the characteristic. If you added a new custom characteristic, you will need to add it to the list of characteristics in the Android app (GattAttributes.java). 

Then, add it to the switch statement in the broadcastUpdate method, the isDataCharacteristic method, and the onCharacteristicRead method in BluetoothLeService.java. Add in Logs here to see if you are capturing the data. Remember to update the methods for saving and clearing data too (saveAgmData and clearDataArrays methods).

More background on this project [here](https://www.hackster.io/dalbaugh/how-to-use-ble-to-connect-arduino-to-an-android-studio-app-163339) in case you found it via GitHub.
